### ISSUE TITLE
Module breaks /e/OS (fork of LineageOS) updater 

### ISSUE THREAD

**Issue by bege10** [ToucH9000/USNFvayuLOS#1]
Hello,
this module works great on two of my devices which both run /e/OS. Thank you!

- Fairphone 3, /e/OS Android 12
- Shiftphone 6mq, /e/OS Android 13

But on both phones the system updater does not work any more as soon as the module is active.

Without module the updater shows the current version and searches for updates.

![Screenshot_20231104-170011_Aktualisierungsprogramm](https://github.com/ToucH9000/USNFvayuLOS/assets/1184237/82334e6e-0d1b-44cb-b5e4-2349981db9eb)

With the module it does not show the current version and search fails.

https://github.com/ToucH9000/USNFvayuLOS/assets/1184237/c6049dec-2b2a-4f2b-b839-3f243fc9f644

(The toast says that the update check has failed and one should check the internet connection - which works correct.)

The current work-around to enable OTA updates is to temporarily deactivate the module.

**Comment by ToucH9000** [comment]
I have added LineageOS hiding properties in USNFvayuLOS, which hides LineageOS existence from detection apps which also confuses updater to which build i am using and i always update with TWRP, i never used updater. This module is only for POCO X3 Pro don't use it for other devices.

**Comment by bege10** [comment]
> I have added LineageOS hiding properties in USNFvayuLOS, which hides LineageOS existence from detection apps which also confuses updater that which build i am using and i always update with TWRP, i never used updater. This module is only for POCO X3 Pro don't use it on other devices.

Thank you for your explanation.
